# Generated by Django 6.0.4 on 2026-04-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('narxi', models.IntegerField(default=0)),
                ('davomiyligi', models.IntegerField(default=0)),
                ('darajasi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('yonalishi', models.CharField(max_length=255)),
                ('ochilgan_sana', models.DateTimeField(auto_now_add=True)),
                ('talabalar_soni', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('dars_soati', models.IntegerField(default=120)),
                ('laboratoriya_borligi', models.BooleanField(default=True)),
            ],
        ),
    ]
