# Generated by Django 6.0.4 on 2026-04-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('tavsifi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=255)),
                ('familiyasi', models.CharField(max_length=255)),
                ('telefon', models.CharField(max_length=255)),
                ('manzili', models.CharField(max_length=255)),
                ('jami_xaridi', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('umumiy_summa', models.CharField(max_length=255)),
                ('tolov_turi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('kodi', models.CharField(max_length=255)),
                ('narxi', models.IntegerField(default=0)),
                ('miqdori', models.IntegerField(default=0)),
                ('ishlab_chiqaruvchi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kompaniya_nomi', models.CharField(max_length=255)),
                ('masul_shaxs', models.CharField(max_length=255)),
                ('telefon', models.CharField(max_length=255)),
                ('yetkazish_muddati', models.IntegerField(default=1000000000)),
            ],
        ),
    ]
