# Generated by Django 6.0.4 on 2026-04-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=255)),
                ('familiyasi', models.CharField(max_length=255)),
                ('lavozimi', models.CharField(max_length=255)),
                ('kirgan_sanasi', models.DateTimeField(auto_now_add=True)),
                ('ish_haqi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raqami', models.CharField(max_length=255)),
                ('qavat', models.IntegerField(default=1)),
                ('turi', models.CharField(max_length=255)),
                ('narxi', models.CharField(max_length=255)),
                ('band_holati', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('janri', models.CharField(max_length=255)),
                ('rejissyor', models.CharField(max_length=255)),
                ('davomiyligi', models.CharField(max_length=255)),
                ('chiqish_yili', models.CharField(max_length=255)),
            ],
        ),
    ]
