# Generated by Django 6.0.4 on 2026-04-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField(auto_now_add=True)),
                ('vaqt', models.TimeField(auto_now_add=True)),
                ('shikoyati', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=255)),
                ('familiyasi', models.CharField(max_length=255)),
                ('mutaxassisligi', models.CharField(max_length=255)),
                ('xona_raqami', models.CharField(max_length=255)),
                ('tajribasi', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('dozasi', models.CharField(max_length=255)),
                ('turi', models.CharField(max_length=255)),
                ('muddati', models.CharField(max_length=255)),
                ('qollash_usuli', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=255)),
                ('familiyasi', models.CharField(max_length=255)),
                ('kasallik_tarixi', models.CharField(max_length=255)),
                ('qon_guruhi', models.CharField(max_length=255)),
                ('yoshi', models.IntegerField(default=0)),
            ],
        ),
    ]
