# Generated by Django 6.0.4 on 2026-04-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markasi', models.CharField(max_length=255)),
                ('modeli', models.CharField(max_length=255)),
                ('rangi', models.CharField(max_length=255)),
                ('davlat_raqami', models.CharField(max_length=255)),
                ('yili', models.IntegerField(default=1850)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=255)),
                ('familiyasi', models.CharField(max_length=255)),
                ('guvohnoma_toifasi', models.CharField(max_length=255)),
                ('tajribasi', models.IntegerField(default=0)),
                ('reytingi', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boshlangich_nuqta', models.CharField(max_length=255)),
                ('yakuniy_nuqta', models.CharField(max_length=255)),
                ('masofa', models.CharField(max_length=255)),
                ('davomiyligi', models.CharField(max_length=255)),
            ],
        ),
    ]
